import "@/styles/global.css";

import type { Metadata } from "next";
import { Providers } from "@/components/Providers";
import { PropsWithChildren } from "react";
import { getServerSession } from "@/lib/auth";
import { Header } from "@/components/Header";

export const metadata: Metadata = {
  title: "Todo",
  description: "Generated by create next app",
};

export default async function RootLayout(props: PropsWithChildren) {
  const { children } = props;
  const session = await getServerSession();

  return (
    <html lang="en">
      <body>
        <Providers session={session}>
          <Header
            user_name={session?.user?.name ?? undefined}
            authenticated={!!session}
          />
          {children}
        </Providers>
      </body>
    </html>
  );
}
